version: 0.0
os: linux

files:
  - source: ./datascine-scripts
    destination: /home/ec2-user/dataciense-project-scripts
    - source: /
    destination: /home/ec2-user/dataciense-project-scripts
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: clear.sh
      timeout: 300
      runas: ec2-user   
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ec2-user
  